// Jenkinsfile
pipeline {
    agent any
    
    stages {
        stage('Checkout') {
            steps {
                checkout scm
                 sh 'pwd'
                 sh 'ls -alh'
            }
        }
        
        stage('Load and Run Groovy Script') {
            steps {
                script {
                    // Load an external Groovy script
                    def myScript = load 'jenkins/greetings.groovy'

                    // Pass parameters to the script
                    myScript(name: 'Brendan', age: 22)
                }
            }
        }
    }
}
